import { mount } from "svelte";
import LegacyToolPage from "../components/LegacyToolPage.svelte";
import "../styles/theme.css";
import "../styles/pages/index.css";

mount(LegacyToolPage, {
  target: document.body,
  props: {
    beforeMenu: "<span class=\"brand\">GB&nbsp;Tool&nbsp;Suite <span class=\"sub\">for DMG / GBC</span></span>\n    <div class=\"spacer\"></div>",
    afterMenu: "<span class=\"target-tag\">no build &middot; no server state</span>",
    content: "<div class=\"hero\">\n    <h1>Game Boy Tool Suite</h1>\n    <p>Build worlds, sprites and chiptunes for GBDK-2020 — and squeeze your\n       art into VRAM — right in the browser.</p>\n  </div>\n\n  <main class=\"tools\">\n    <a class=\"tool-card\" href=\"gb-world-editor.html\">\n      <canvas id=\"preview-world\" width=\"160\" height=\"48\"></canvas>\n      <h2>World Editor</h2>\n      <p>Draw 8&times;8 tiles, compose metatiles and blocks, paint maps, place\n         warps and events. Exports .gbworld.json, convertible to GBDK-2020 C.</p>\n      <span class=\"go\">Open editor &raquo;</span>\n    </a>\n    <a class=\"tool-card\" href=\"gb-sprite-editor.html\">\n      <canvas id=\"preview-sprite\" width=\"160\" height=\"48\"></canvas>\n      <h2>Sprite Editor</h2>\n      <p>Draw or import sprite sheets, arrange 8&times;8 / 8&times;16 hardware\n         sprites into metasprites, and sequence them into animations. Exports\n         .gbsprite.json and PNG.</p>\n      <span class=\"go\">Open editor &raquo;</span>\n    </a>\n    <a class=\"tool-card\" href=\"gb-music-generator.html\">\n      <canvas id=\"preview-music\" width=\"160\" height=\"48\"></canvas>\n      <h2>Music Generator</h2>\n      <p>A deterministic four-channel chiptune improviser. Pick key, mood,\n         pattern and seed; export settings as .gbmusic.json or a MIDI file.</p>\n      <span class=\"go\">Open generator &raquo;</span>\n    </a>\n    <a class=\"tool-card\" href=\"gb-sfx-generator.html\">\n      <canvas id=\"preview-sfx\" width=\"160\" height=\"48\"></canvas>\n      <h2>SFX Generator</h2>\n      <p>Design Game Boy sound effects from presets (coin, laser, jump,\n         explosion&hellip;), refine with semantic sliders, and export\n         .gbsfx.json, a WAV, or GBDK-2020 C with a tiny player.</p>\n      <span class=\"go\">Open generator &raquo;</span>\n    </a>\n    <a class=\"tool-card\" href=\"gb-pixelizer.html\">\n      <canvas id=\"preview-pixelizer\" width=\"160\" height=\"48\"></canvas>\n      <h2>Pixelizer</h2>\n      <p>Turn any image into 2-bit pixel art: tone controls, pixel-art-aware\n         downscaling (k-centroid and friends), optional dithering, and a live\n         tile-count readout.</p>\n      <span class=\"go\">Open pixelizer &raquo;</span>\n    </a>\n    <a class=\"tool-card\" href=\"gb-tile-reducer.html\">\n      <canvas id=\"preview-reducer\" width=\"160\" height=\"48\"></canvas>\n      <h2>Tile Reducer</h2>\n      <p>Load a PNG, count its unique 8&times;8 tiles, and merge similar ones\n         until the image fits your VRAM budget while staying close to the\n         original.</p>\n      <span class=\"go\">Open reducer &raquo;</span>\n    </a>\n  </main>\n\n  <footer>Everything runs locally. Projects live in exported files, not the browser.</footer>",
    currentPage: "",
    initialize: () => import("../legacy/index.js"),
  },
});
